language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo rm -f /etc/boto.cfg  # https://github.com/travis-ci/travis-ci/issues/7940
install:
  - pip install --verbose -r requirements.txt
script:
  - DEEPDRIVE_DIR=/tmp/testdeepdrive pytest tests/test_sanity.py