version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          ENABLE_SIM_BUILD: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - dd-dependencies-{{ checksum ".ci/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - dd-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r .ci/requirements.txt
            pip install --upgrade --force-reinstall --ignore-installed --no-cache-dir git+git://github.com/botleague/botleague-helpers#egg=botleague-helpers
            pip install --upgrade --force-reinstall --ignore-installed --no-cache-dir git+git://github.com/deepdrive/problem-constants#egg=problem-constants

      - save_cache:
          paths:
            - ./venv
          key: dd-dependencies-{{ checksum ".ci/requirements.txt" }}

      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run:
          name: Build containers and run botleague CI
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            . venv/bin/activate
            cd .ci && make run
            python -u cloud_ci.py

